### PR TITLE
(Windows) Add command line information to process listing when injecting

### PR DESCRIPTION
**Pull request by tasgon**
## Description

I found it difficult to try and differentiate things like Java or Python programs in the process table when I was injecting, so I added command line information to the process table so it would be easier to identify which process you actually want to inject into.

### CODE REVIEW

**Comment by baldurk** [comment]
Process injection can be unreliable and I strongly recommend against ever using it - it is almost never a good idea. I made the feature opt-in to since too many users were accidentally stumbling onto it when they should have been launching their programs as normal.

I consider this feature completely frozen so I don't want to add any changes like this. The only reason I don't remove it entirely is because I have a policy not to remove features from RenderDoc that people might be using (even though in the case of this one they almost certainly shouldn't be using it).

**Comment by tasgon** [comment]
How, then, do you recommend handling projects that are not launched directly? For example, one of the projects I'm working on uses Gradle, and the launching process starts with `gradlew.bat`, which then starts actual Gradle process, which then starts the program in question.

While the normal launcher allows capturing child processes, it doesn't seem to capture children of children. Would that feature be acceptable to add, and/or am I using the software incorrectly?

**Comment by baldurk** [comment]
Generally I'd recommend making your process launch simpler and more direct as this has benefits for other tools and scenarios as well, but if it's unavoidable then you can indeed use a wrapper script and configure child process capture.

This does work recursively - though it has a limit on the number of processes that will be connectable to avoid some kind of runaway scenario, so if you need to spawn more than half a dozen processes that would have issues. If you have a simple case of process A -> B -> C then that should work fine and it is a bug if it does not.

**Comment by tasgon** [comment]
> If you have a simple case of process A -> B -> C then that should work fine and it is a bug if it does not.

That should be the case I'm dealing with here, so then it does seem to be a bug.

Also, another thing I've been thinking about is if I want to use both my IDE's debugger and Renderdoc at the same time, how should I go about doing it if both platforms want to be the one to launch the program in question?

**Comment by baldurk** [comment]
There's an option 'delay for debugger' which allows you to specify a delay upon launching a process where you can attach a CPU debugger.

**Comment by tasgon** [comment]
That would only delay the launch of the initial process, not of subsequent ones, right?

**Comment by baldurk** [comment]
The same delay will apply to all child processes (recursively) if they're being hooked.

All this being said, generally for ease of use I tend to suggest that if you need to debug your program on the CPU that you do that on its own without involving RenderDoc, and if you need to debug the GPU work then you do that just with RenderDoc and don't try to involve any IDE/debugger. It's rare in practice to need to debug your program on the CPU while RenderDoc is active simultaneously, especially since in principle RenderDoc should be entirely transparent to the application. This is more useful for myself or anyone else developing on RenderDoc who needs to debug the capture process itself.

**Pull request closed without merging**
