### PR TITLE
Enable SPIR-V External Disassembler Tool

### PR DESCRIPTION
**Pull request by adrianbu**
renderdoc_vulkan_external_disassembly

- Added the ability to select an external SPIR-V disassembler and to use
  it for editing any of the shaders in the pipeline.
  Tested with SPIRV-Cross (https://github.com/KhronosGroup/SPIRV-Cross)
  Fragment, Vertex, Geometry, Compute shaders

### CODE REVIEW

**Comment by adrianbu** [comment]
Thanks for your suggestions - I'll make the updates

**Comment by adrianbu** [comment]
I've made the changes you requested so please take a look.

**Comment by baldurk** [comment]
For future reference - with review updates and further changes, please don't rebase and squash them into the original commit. This means I can't see directly what's changed between the original commits and the new, and that kind of change is useful history to have. Rebasing is fine (and encouraged!) for small things that shouldn't clutter history like typos, formatting changes, etc, or avoiding merge commits by rebasing onto latest master.

**Comment by adrianbu** [comment]
OK. That makes sense - I will keep the history with additional commits in the future. I guess we can rebase at the end of the review process if necessary.

**Comment by baldurk** [comment]
Right, as a broad strokes idea a good workflow would be:

1. Work locally with whatever commits/branching/rebasing strategy is appealing to you.
2. When you're ready to create the new PR, rebase onto the current latest master. Remove any merge commits you might have, tidy up the commit messages and ordering as relevant, and make sure commits are formatted. It's easier if you stick to that all along, but it's up to you.
3. Push the PR, have a review and discussion, etc.
4. If any changes need to happen then go back to 1. and make them all locally with whatever works, and rebase them as in 2. but only rebase the new changes - so at minimum there would be a 'Update for review feedback' commit, maybe a couple of commits if it makes sense logically.

I don't want to be too prescriptive about how people do things since that's unnecessary and annoying. What I'm after is primarily keeping a clean history without merge or format-only commits, and making reviews easier as a secondary concern. That means rebasing is good for removing formatting or typo fixes etc before pushing, but ideally would be avoided after pushing if possible to keep the review easier to track. Neither is the end of the world though.

I'm not really fussed about how many commits you make in a PR and whether it contains 'internal' changes or squashes work together. I'm not really a fan of the extreme of always squashing PRs into a single commit, as sometimes it can be much easier to follow with several commits. For example - Add a new feature to some interface, then a commit each for implementing it in Vulkan, D3D11, GL.

**Pull request merged**
