### PR TITLE
Test Android target connection for an adjustable period of time.

### PR DESCRIPTION
**Pull request by michaelrgb**

### CODE REVIEW

**Comment by baldurk** [comment]
Hmm, I'm not entirely sure about this. If I understand the implementation exactly, the delay is being used to determine how long to wait for the application to start up on the android device, where previously it was a flat 5s.

That doesn't match what the option is documented and described as doing though, which is to delay the application immediately after it starts up to allow a debugger to attach and still debug from the beginning (rather than trying to attach as quickly as possible after RenderDoc launches the program and finding you missed some init code you wanted to debug).

So in that respect I think this would maybe be better being added as a global option in the settings menu under android? similar to the adb path, it could be a configuration option there.

**Comment by michaelrgb** [comment]
Yes I have an app that takes about 17 seconds to load before Vulkan & the capture layer are ready to receive a connection.

I will add a "Max Connection Timeout" to the Android settings page, and default it to 30 seconds.

**Comment by michaelrgb** [comment]
I have added the global option in the Settings dialog, and I passed it into the native code via a new member variable in CaptureOptions: MaxConnectTimeout.

On second thoughts it might be better to get it via the RenderDoc::Inst().GetConfigSetting("") function. Would you prefer that?

**Comment by baldurk** [comment]
Yes I think going via `GetConfigSetting`/`SetConfigSetting` is better as this isn't a setting you're likely to want to configure on a per-capture basis.

I wonder if we'll need a better way of propagating those settings from the UI into the core. At the moment it's a bit ad-hoc, but it'd be nice at some point to not have to have them spread around.

**Pull request merged**
