### PR TITLE
Support VK_EXT_primitive_topology_list_restart

### PR DESCRIPTION
**Pull request by ShabbyX**
## Description

This extension exposes a capability that pretty much all devices already
had.  It allows list topologies to be used with primitive restart.

### CODE REVIEW

**Review by baldurk — CHANGES_REQUESTED** [review]
This looks good, thanks.

In this case I think that the state and display UI probably already works (though it's worth double checking), since I don't think I had any special case code to only conditionally display the restart state. Unfortunately though I don't think the mesh view will work correctly for this as I believe it will only process primitive restart for strip topologies. Can you test to make sure that the mesh viewer is working an apply any fixes as well that are needed for proper display of inputs and outputs?

I never supported this on GL because I didn't even realise it was legal honestly, and it sounds like one of the GL things which is too stupid an idea to support. Making the fixes work on GL would be a welcome bonus, but isn't required for this PR.

**Comment by ShabbyX** [comment]
Done. The UI now takes primitive restart into account for list topologies too. I tested this on Vulkan, but pretty sure it's fine for the other APIs too. I don't have access to D3D at all, and unfortunately have nothing readily available to test OpenGL (I'm trying in the meantime to see about building the deqp for GL).

**Comment by ShabbyX** [comment]
Yeap, I can confirm it works on GL too. Again, I don't have access to D3D to test it

**Comment by baldurk** [comment]
I double checked on the D3D11 spec expecting it to be left undefined, but it seems like this behaviour is there. Though they have a note calling it out as pointless and applications shouldn't use it (as you'd expect):

> Even if the current Primitive Topology is not a strip, then the cut index value still takes effect, potentially resulting in an incomplete primitive (see next section). Thus, handling of the cut is kept orthogonal to primitive topology, even though it is not useful for some of them.
>
> Note that providing a behavior for the cut value when used with a non-strip topology is a way of saying that the behavior is defined, allowing hardware to keep the cut behavior always enabled. In practice though, using cut for a list topology is obviously not a "feature" that it would ever make sense for an application to author to.

I'll make a follow-up commit and double-check the behaviour with D3D which should follow naturally from your changes, thanks for looking into that.

**Pull request merged**
