### PR TITLE
Update HWCPipe to support performance counters of Dimensity 9000 SoC

### PR DESCRIPTION
**Pull request by ming4883**
## Description
Since the bundled version of HWCPipe is a little bit out-of-date (2019), the performance counter feature does not work on recent Mali GPUs (e.g. Mali-G710)

The PR update the HWCPipe to a more recent version plus one bug fix, so that performance counter can work up to Dimensity 9000 SoC (Mali-G710).

More information about the HWCPipe bug fix can be found [here](https://github.com/ARM-software/HWCPipe/issues/57).

---
update 2022-04-29
Base HWCPipe commit SHA: [8cc02065b4ef249127aa0164dc0d62d65c0d4203](https://github.com/ARM-software/HWCPipe/commit/8cc02065b4ef249127aa0164dc0d62d65c0d4203)

### CODE REVIEW

**Comment by baldurk** [comment]
Can you please mention the specific commit hash that you copied HWCPipe from in the commit message itself? It makes it easier to track in future what version exactly we're using. Otherwise this is fine, thank you.

**Comment by ming4883** [comment]
Sorry for missing this important information, I have updated the PR description and commit message to include the SHA of both the base HWCPipe commit; and the proposed bug fix commit.

**Comment by baldurk** [comment]
I did not realise this included changes which haven't been merged into the upstream repository.

This should wait until it has been merged, I have no way of reviewing or verifying any changes so it would have to be merged upstream before I would include it here.

**Comment by ming4883** [comment]
@baldurk 
The purposed bug fix for HWCPipe had been verified and accepted. 
https://github.com/ARM-software/HWCPipe/commit/8cc02065b4ef249127aa0164dc0d62d65c0d4203

So this PR is safe to be merged into renderdoc.

**Pull request merged**
