### PR TITLE
Ignore apps requesting VK_ANDROID_native_buffer, instead of failing.

### PR DESCRIPTION
**Pull request by michaelrgb**

### CODE REVIEW

**Comment by michaelrgb** [comment]
This is slightly hacky in that we are claiming support just to make RenderDoc ignore that extension. Perhaps WrappedVulkan::vkCreateInstance() should have a separate list of extensions that it ignores?

**Comment by baldurk** [comment]
I'm not sure which way to go on this. If we claim to support an extension then we must really support it. It's not in the spirit of Vulkan to work around application bugs by allowing things that aren't valid.

That said, in vk.xml there isn't any actual interface defined for the extension - no structs or functions associated with it. If the extension is just something like the SPIR-V marker extensions which have no interaction with the API except to signal some usage, then I think it's probably fine to claim support because we do technically support it (even if that actually amounts to no-op).

So that's the question - is there actually an interface for the extension or is it just a marker/toggle by its presence alone? If it's a "real" extension then I don't want to claim support on the assumption that applications are only accidentally requesting it and we don't think they'll _really_ use it.

**Comment by michaelrgb** [comment]
The interfaces provided are only for the Android WSI implementation, not for use by apps, so I think that vk.xml doesnt document them because no one needs to know.

The extension does provide the following APIs and type, as described in that Android page:
vkGetSwapchainGrallocUsageANDROID()
vkAcquireImageANDROID()
vkQueueSignalReleaseImageANDROID()
VkNativeBufferANDROID

My particular app doesnt call them, it just asked for that extension for no apparent reason, and Im sure no other app would ever want to call those APIs. It would be nice for RenderDoc to just work here without having to republish the app, but I understand if thats a slippery slope.

**Comment by baldurk** [comment]
Right, my concern is though that if we report a supported extension that doesn't actually work. In the future there might be a reason for applications to call those functions, or possibly you could try and call them yourselves now (I don't know if the ICD would return valid function pointers if requested?). At that point they will likely explode because RenderDoc isn't unwrapping objects properly as they pass through.

Aside from the vulkan philosophy of not trying to workaround buggy programs, we need to be particularly careful with extension support due to the object wrapping. Since you say that this extension shouldn't be requested by applications then I'd rather not allow it in RenderDoc. It could be thought of as a poor man's validation I suppose.

**Pull request closed without merging**
