### PR TITLE
Added SV_RenderTargetArrayIndex support to pixel shader debug

### PR DESCRIPTION
**Pull request by deM-on**
Added SV_RenderTargetArrayIndex support to pixel shader debug - fix for #1527

### CODE REVIEW

**Comment by baldurk** [comment]
I appreciate the contribution but while it solves your problem I don't want to merge this upstream. This fix only covers specific cases, and I'd rather fix this with a solution that covers everything. As discussed in #1527 this is a subset of #763 and is not orthogonal.

The root problem is that the pixel shader debugging currently only disambiguates on primitive ID for multiple writes to a single sample/fragment. When using instancing the same primitive ID can write multiple times to the same sample, but sourced from different instances so with different inputs.

In your case, the instance ID is passed along to the pixel shader via `SV_RenderTargetArrayIndex`, but there's not necessarily a direct correlation. If instead of having a draw with a single quad instanced N times, you had N quads which each went to a different RT index then the debugging would be able to disambiguate purely based on primitive ID without needing this extra code. Similarly if you had a draw where multiple instances went to the same RT index and overdrew then this code would not fix the problem because the array index no longer fully disambiguates which sample to debug.

**Comment by deM-on** [comment]
#763 describes a problem where you can't distinguish fragments touching **same** pixel. 
But in #1527 they are **different** pixels, to begin with. You have x and y already. This adds "z".

**Comment by baldurk** [comment]
I see where you're coming from - in my mental model all samples and slices are still part of the same pixel, it can just be an arrayed or multi-sampled (or both) pixel. So the problem is framed in terms of debugging the desired write to that pixel via filtering on the inputs.

Viewing them as different pixels the semantics are still problematic. With the sample index we can always use `SV_Coverage` to know what sample we're writing to, so we can implicitly filter pixel shader invocations to only the desired sample, the same as we do with primitive ID. With array/slice index we can't do that - `SV_RenderTargetArrayIndex` is only valid to read if it was written by the previous shader stage, it doesn't automatically populate with the index being written to.

I'm not saying that your solution doesn't work or help in some scenarios, but I'm concerned about adding a partial solution to fix some of the problems when it still leaves a gap that needs to be fixed - and the solution for the larger problem will also solve this problem.

**Comment by deM-on** [comment]
Well, IMO it doesn't matter what kind of mental models either of us has. It's about interface RD provides - user selects slice and sample number first, then picks pixel and press debug. I'd expect to debug **this** pixel, not additional interface or list of fragments to pick from.

Also, AFIAK, `SV_RenderTargetArrayIndex` is the **only** way to draw in different slices of RT array (and cube maps), so I don't really see how this issue can be solved w/o using it.

The only problem I see with my commit is UB if `SV_RenderTargetArrayIndex` is not set by GS. I can't find any info on how it should behave, even if on my PCs it just set to 0 (which makes sense - if it's not set pixel must be written to slice 0). If you think it can cause problems it is easy to add a check for input signature (I can do it)

**Comment by baldurk** [comment]
As I mentioned this only solves the case where you have each instance rendering to its own array index. If you had an instanced draw where multiple instances could render to the same array index, `SV_RenderTargetArrayIndex` would no longer work to disambiguate but the instance would - and disambiguating by instance would also solve this case. I don't want to merge and support this partial solution, which will later need to be superceded by another.

Again you can keep this change locally for your own use, it's only that I don't want to include it upstream. I appreciate you making the change and I'm glad you were able to find a solution for your problem, but I'm not going to merge this PR.

**Pull request closed without merging**
