### PR TITLE
Save in app's own /sdcard directory, doesnt need WRITE_EXTERNAL_STORAGE.

### PR DESCRIPTION
**Pull request by michaelrgb**

### CODE REVIEW

**Comment by michaelrgb** [comment]
Perhaps @cnorthrop would like to review? This is a useful step in making RenderDoc "just work" for more apps.

**Comment by cnorthrop** [comment]
I've been meaning to try this experiment.  Kind of freaky that the server app can read the app's data on sdcard, but I guess that's what `READ_EXTERNAL_STORAGE` is for.  I'll test this PR with some apps that I know suffer from lack of this permission.

**Comment by baldurk** [comment]
Possibly a silly question - does this "just work" when the device doesn't have an SD card? is it just emulated by the OS and `/sdcard` doesn't necessarily correspond directly to an SD card, or is it up to the application to try/fallback to a different location?

Is there a significant difference in available bandwidth, between SD card and the onboard storage?

**Comment by cnorthrop** [comment]
Yes, /sdcard is just a symlink to mounted storage, which may or may not be a physical card.  None of my devices actually has a physical sdcard:

```
$ adb shell
marlin:/ # ls -la /sdcard
lrw-r--r-- 1 root root 21 2009-01-01 00:00 /sdcard -> /storage/self/primary
marlin:/ # ls -ls /storage/self/primary
0 lrwxrwxrwx 1 root root 19 1971-01-28 11:38 /storage/self/primary -> /mnt/user/0/primary
```
I'm fairly certain (just from my own perspective, not a Google proper statement) that we are always guaranteed to have an /sdcard on the filesystem.  It seems inherent to Android and most applications expect it to be there.  I should try using an sdcard through a USB-C adapter to see how it behaves sometime.

**Comment by cnorthrop** [comment]
Okay, with the fixes to get Android tracing going again, I've tried this commit out.  It needs a few more changes to update the Android workflow.  Basically just removing more checks.  I made them here if you want to grab them:

>android: Remove checks for WRITE_EXTERNAL_STORAGE from Android workflow
>https://github.com/cnorthrop/renderdoc/commit/719c1944a578632f88d8207993ed9a4dcb64df8d

With those, I was able to trace an app that didn't have `WRITE_EXTERNAL_STORAGE` permission, so kudos for the find!

**Comment by baldurk** [comment]
@michaelrgb I'll merge either if you add the extra change or say you'd like to take this as-is.

**Comment by michaelrgb** [comment]
Removed the checks too, thanks!

**Pull request merged**
