### PR TITLE
GLWindowingData context functions are now virtual methods.

### PR DESCRIPTION
**Pull request by michaelrgb**
On Linux we inherit into GLXWindowingData and EGLWindowingData.
GLWindowingData is passed around by value, so the copy constructor and
assignment operator keep the vtable.

### CODE REVIEW

**Comment by baldurk** [comment]
I don't like this solution, relying on memcpy to grab the vtable is very and it looks like clang has a warning that fires on this specifically.

There are a couple of solutions that I think are much better:

First option would be to make those functions a pure virtual interface, and implement it in the `EGLHook` / `OpenGLHook` classes. Every place that `WrappedOpenGL` is constructed we know which platform we're working with, so we can pass in a pointer to the appropriate instance that implements the interface, and `WrappedOpenGL` can store it for use. E.g.:

```cpp
struct GLPlatform
{
  virtual GLWindowingData MakeContext(GLWindowingData share) = 0;
  virtual void DeleteContext(GLWindowingData context) = 0;
  virtual void MakeContextCurrent(GLWindowingData data) = 0;
};

class OpenGLHook : LibraryHook, public GLPlatform
{
  // ...
  WrappedOpenGL *GetDriver()
  {
    if(m_GLDriver == NULL)
      m_GLDriver = new WrappedOpenGL("", GL, this);

    return m_GLDriver;
  }
}

const GLPlatform *GetDesktopGL()
{
  return &OpenGLHook::glhooks;
}

ReplayCreateStatus GL_CreateReplayDevice(const char *logfile, IReplayDriver **driver)
{
  // ...
  WrappedOpenGL *gl = new WrappedOpenGL(logfile, real, GetDesktopGL());
  gl->Initialise(initParams);
}

// .. etc, now WrappedOpenGL calls through the passed in GLPlatform * as needed.
```

This would be my preferred solution as it avoids any #ifdefs.

The other alternative is to do the dispatch still with the C-style functions. Put them in a common file which is always compiled, and add a `bool isEGL` flag or something into the GLWindowingData so that it can do something along the lines of:

```cpp
void MakeContextCurrent(GLWindowingData data)
{
#ifdef RENDERDOC_SUPPORT_EGL
  if(data.isEGL)
  {
    EGLHook::glhooks.MakeContextCurrent(data);
    return;
  }
#endif

  OpenGLHook::glhooks.MakeContextCurrent(data);
}
```

Side note - I think the immediateBegin/immediateVert/immediateEnd can just be refactored into a single `drawQuads` function that takes a `std::vector<Vec4f>` for the data.

**Comment by michaelrgb** [comment]
I like option 1 too. On the way.

The immediate* quad refactor can be in a separate commit, but it will also need to go into the GLPlatform because there is lots of platform-specific stuff there.

**Comment by baldurk** [comment]
That's fine, you can do it either way around. As you say it would need to go in as a virtual function too, I mentioned it in case you'd find it easier to make that change at the same time to simplify the interface.

**Comment by michaelrgb** [comment]
Hmm In hooks_linux_shared.cpp, every HookWrapper* function calls GetDriver(), which creates the WrappedOpenGL. The problem is that is shared code so we dont know whether to create it with the EGL or GLX GLPlatform. I think its Ok to just use m_GLDriver->function() because those wrapper functions will be called AFTER the glXCreateContext/eglCreateContext, which call GetDriver() in the non-shared code.

**Comment by baldurk** [comment]
Yes I'd agree, it should be fine just to skip the lazy creation of the driver in the shared code. In fact most of the internal functions will break if they are called before context creation, even aside from this issue.

On windows the functions have a bool `m_HaveContextCreation` which tracks if context create has been hooked, and if it hasn't then it forwards directly onto the 'real' function instead of going through the hook. However that's only there to make sure that things behave sanely when a program is injected late and GL has already been initialised. On non-windows we only support hooking from program startup, so it's not necessary, but in theory we could use the same fix there in future.

**Comment by michaelrgb** [comment]
Just copying my commit to my Windows box to do that side too...

Youre right it was easier to refactor into drawQuads(). Will include that here.

**Comment by michaelrgb** [comment]
After today's EGL commit, we now have multiple definitions of GLReplay::SwapBuffers etc, but I can fix that in a separate commit by moving that stuff into the GLPlatform interface.

**Comment by baldurk** [comment]
That makes sense. I think those functions can stay in gl_replay_egl.cpp / gl_replay_linux.cpp for the sake of organisation (vs the gl_hooks_egl.cpp) but yeh the 'trick' of conditionally compiling some GLReplay implementations sort of breaks now.

Also check the commit message - the first line is being truncated as it's a bit too long.

**Comment by michaelrgb** [comment]
Done.

**Comment by baldurk** [comment]
I think I've merged this correctly, but it had some conflicts with #514 - @galpeter and @michaelrgb please check when you next pull that everything is working as you expect it to.

**Pull request closed without merging**
