### PR TITLE
Disallow the linker to ingore shared libraries during linking

### PR DESCRIPTION
**Pull request by galpeter**
In some cases when the renderdoccmd is linked the linker
ignores the libEGL.so and only uses the librenderdoc.so.
This is because the renderdoc shared library provides the
same symbols as the libEGL.so. However we need to keep the
libEGL.so as we are using RTLD_NEXT in the renderdoc shared
library.

### CODE REVIEW

**Comment by baldurk** [comment]
Nice, I didn't realise this was an option that existed. Does that mean we can get rid of the hacks in [renderdoccmd](https://github.com/baldurk/renderdoc/blob/master/renderdoccmd/renderdoccmd_linux.cpp#L364-L379) and [qrenderdoc](https://github.com/baldurk/renderdoc/blob/master/qrenderdoc/Code/qrenderdoc.cpp#L38-L53) to functions that the renderdoc library doesn't export, to force inclusion of libGL/libEGL?

```cpp

  volatile bool never_run = false;

#if defined(RENDERDOC_SUPPORT_GL)

  if(never_run)
    glXWaitX();

#endif

#if defined(RENDERDOC_SUPPORT_GLES)

  if(never_run)
    eglWaitGL();

#endif
```

If so that's really nice as it's always been an ugly wart. Can you check if it's possible to remove that code and include it in this PR?

I guess this changed because in #567 you exported `eglWaitGL` with the rest of the pass-through functions, but I don't currently export `glXWaitX` for glx to allow this hack to work (which could also be added to [glx_hooks_linux.cpp](https://github.com/baldurk/renderdoc/blob/master/renderdoc/driver/gl/glx_hooks_linux.cpp)).

**Comment by galpeter** [comment]
@baldurk yeah I'll can try it out with renderdoccmd and yes the #567 was the reason for the change.

**Comment by galpeter** [comment]
@baldurk btw it seems that the mac does not support this option :(

**Comment by baldurk** [comment]
Right I think mac will need its own solution for hooking so I don't even know if it will run into the same problems as LD_PRELOAD and exporting all the same functions. It doesn't work yet, it's just in CI to make sure that we don't accumulate compile errors.

If you just change the cmake file so it only adds this option for non-mac, that's fine.

**Comment by galpeter** [comment]
I've update the PR: after removing the `eglWaitGL`/`glXWaitX` calls it seems that it works correctly. Tested with renderdoccmd and ldd checked for qrenderdoc.

**Pull request merged**
