### PR TITLE
[EGL] Force context change when querying surface dimensions

### PR DESCRIPTION
**Pull request by galpeter**
On some Linux system the eglQuerySurface is unable to query
the surface dimensions if the context is not the same
as when it was created.

### CODE REVIEW

**Comment by galpeter** [comment]
Without this context change, on my system the qrenderdoc only shows a black image in the place of textures as the surface dimension was incorrect.

**Comment by baldurk** [comment]
That's annoying, but this seems like a reasonable fix.

Is that behaviour allowed by the spec, or is it worth reporting this upstream as a bug? I'll merge this either way.

**Comment by baldurk** [comment]
FYI when you come back to fix that formatting issue, there will be a slight conflict if you rebase against head - I've changed `ToStr::Get` to just `ToStr` now.

**Comment by galpeter** [comment]
Sadly I did not find any information about if the surface query should depend on the context or not. I don't know if this is a bug or not in the spec/driver/library.

Also I've rebased the change.

**Pull request merged**
