### PR TITLE
fix hook problem

### PR DESCRIPTION
**Pull request by feng716**
## Description

eglCreateWindowSurface has been replaced by eglCreateWindowSurfaceEXT. This pull request provide the support for hooking eglCreateWindowSurfaceEXT.

### CODE REVIEW

**Comment by Zorro666** [comment]
Hi there

Would you be able to give more background to the requirement for the change. The issue linked in the commit message does not appear to discuss or mention these APIs. 

Where are the new EXT functions defined in a public spec and why are the EXT versions required to be supported instead of the existing non-EXT APIs?

A specification is required to be able to understand the EXT API.  

It is unclear what  (or which platform) requires this change and why the existing non-EXT APIs can't be used. EGL on Android does not appear to need these EXT APIs.

Thanks

**Comment by feng716** [comment]
on my archlinux, renderdoc failed to capture application with gflw. If I open the log option, it wil yield an error(RenderDoc::AddFrameCapturer)
```cpp
  if(devWnd.device == NULL || devWnd.windowHandle == NULL || cap == NULL)
  {
    RDCERR("Invalid FrameCapturer %#p for combination: %#p / %#p", cap, devWnd.device,
           devWnd.windowHandle);
    return;
  }
```
which is basically caused by the null pointers. They are first initialized in the `eglCreatePlatformWindowSurface_renderdoc_hooked`. But glfw ([b35641](https://github.com/glfw/glfw/tree/b35641f)) uses eglCreatePlatformWindowSurfaceEXT to create egl surfce
```c
        window->context.egl.surface =
            eglCreatePlatformWindowSurfaceEXT(_glfw.egl.display, config, native, attribs);
```
Since renderdoc cannot hook this function, the handle remains null.

Im sorry cuz there is no `eglCreateWindowSurfaceEXT`. there is only `eglCreatePlatformWindowSurfaceEXT`. I will delete them in the commit.

I think this is the [registry](https://registry.khronos.org/EGL/extensions/EXT/EGL_EXT_platform_base.txt)

**Comment by Zorro666** [comment]
Thank you for explain the rationale for the change. 
This seems like a problem in GLFW which is using the EXT API instead of the Core API.
Another question: is it intentional to be using EGL on a desktop instead of GLX?

The circumstances for this problem seem to be quite specific and haven't been reported before.

Perhaps it is simpler to change the application to match the existing supported APIs i.e.  eglCreatePlatformWindowSurface

**Comment by feng716** [comment]
It seems adding the eglCreatePlatformWindowSurfaceEXT is intended to support for headless renderer.

According to [the registry](https://registry.khronos.org/EGL/extensions/EXT/EGL_EXT_platform_base.txt), 
```
    The behavior of eglCreateWindowSurface is identical to that of
    eglCreatePlatformWindowSurfaceEXT except that the set of platforms to
    which <dpy> is permitted to belong, as well as the actual type of <win>,
    are implementation specific.
```
Also on wayland glfw provides no options for creating glx context because:
```
GLFW_CONTEXT_CREATION_API specifies which context creation API to use to create the context. 
Possible values are GLFW_NATIVE_CONTEXT_API, GLFW_EGL_CONTEXT_API and GLFW_OSMESA_CONTEXT_API. 
This is a hard constraint. If no client API is requested, this hint is ignored.

Wayland: The EGL API is the native context creation API, so this hint will have no effect.
```
if someone wants to fix this problem on wayland with glfw, it is required to modify the source file.

**Comment by Zorro666** [comment]
Thank you for explaining and chasing down.
One comment it is an odd choice for GLFW to use `eglCreatePlatformWindowSurfaceEXT` instead of `eglCreatePlatformWindowSurface` (it makes sense to migrate from `eglCreateWindowSurface`). 

Does this problem only happen on Wayland? Can you try on X11 or with the Wayland X compatibility layer.

The reason for asking is RenderDoc does not have native support for Wayland.

**Comment by feng716** [comment]
This is a problem of wayland in glfw.

I compille the glfw with the option `GLFW_BUILD_X11=ON` and `GLFW_BUILD_WAYLAND=OFF`, renderdoc works for the  capture.

If renderdoc does not plan to have support for wayland, should i close this pr?

**Comment by Zorro666** [comment]
Thank you chasing down and getting to the root cause of the problem. Closing this PR because it is not needed when not using Wayland.

**Pull request closed without merging**
