### PR TITLE
Add strings for new VK_KHR_maintenance2 depth/stencil layouts

### PR DESCRIPTION
**Pull request by aejsmith**

### CODE REVIEW

**Comment by baldurk** [comment]
This is fine but bear in mind that VK_KHR_maintenance2 isn't whitelisted in the extension list, so it won't be reported as supported to any applications. I need to go through and make sure I can support the other features added - it'll need some serialisation of pNext structures I think.

**Comment by aejsmith** [comment]
Hah, that'd explain why I'm not seeing those layouts used where I was expecting them :) Fair enough.

**Comment by aejsmith** [comment]
Should it be safe for me to whitelist it locally if the only thing I'm using from it is those new layouts?

**Comment by baldurk** [comment]
That _should_ be safe, but I don't make any guarantees :smile:.

**Comment by aejsmith** [comment]
Yep, seems to work OK. Feel free to close this and just leave it to whenever you add full support for maintenance2.

**Comment by baldurk** [comment]
OK. I do plan to do another pass on vulkan extensions soon, since I think there are a few now like maintenance2 that I should be able to support without too much difficulty and are in common use.

**Pull request closed without merging**
