### PR TITLE
Support VK_EXT_rasterization_order_attachment_access

### PR DESCRIPTION
**Pull request by ShabbyX**
This change adds support for the `VK_EXT_rasterization_order_attachment_access` extension. This extension basically adds just a few flags to obviate the need for a subpass self-dependency, and is used to implement behavior similar to coherent framebuffer fetch in GLES.

### CODE REVIEW

**Review by baldurk — CHANGES_REQUESTED** [review]
This implementation is incomplete, you are not correctly handling the features struct and without that this cannot be sufficient to validly capture any program using the extension.

**Comment by ShabbyX** [comment]
> This implementation is incomplete, you are not correctly handling the features struct and without that this cannot be sufficient to validly capture any program using the extension.

Ugh sorry, totally forgot. Done.

**Comment by baldurk** [comment]
This should also have the feature checks added into the others in `Serialise_vkCreateDevice` (`CHECK_PHYS_EXT_FEATURE` etc) to make sure the features used in the capture are available on replay and gracefully fail to open the capture. If you look at previous commits that add extension support you'll see the same pattern.

Has this change been tested on an application using the extension, or is this implemented purely against the spec? The original version shouldn't have worked at runtime and some of the force-pushed updates don't seem like they would have compiled since they had duplicate case statements.

**Comment by ShabbyX** [comment]
Yes actually, I did try the original version and I could capture/replay just fine. The symptoms of the replay being done wrong is synchronization errors, but syncval doesn't support this ext yet anyway (and generates the same synchronization errors either way), which is probably why I didn't notice the ext is not really working in replay.

The intermediate force pushes not building was just myself being hasty with a push :-S

---

I was following VK_EXT_primitives_generated_query, but looks like I missed the changes in `Serialise_vkCreateDevice` for that extension too, I'll fix both.

**Comment by ShabbyX** [comment]
I think I got them all now

**Pull request merged**
