### PR TITLE
Set up Travis CI

### PR DESCRIPTION
**Pull request by cgmb**
It might be a good idea to have a CI server build the software after each change. Travis CI is probably not the best for this, because they're Ubuntu-only, but they're also simple and free for OSS. It's easy to switch providers in the future once a better solution is found.

You'd need to sign up at [travis-ci.org](https://travis-ci.org), link that account with your GitHub account, and enable the service for this repository. Then, each push and pull-request would automatically be built and marked pass or fail. The detailed results look [like this](https://travis-ci.org/cgmb/renderdoc/builds/122719363).

### CODE REVIEW

**Comment by baldurk** [comment]
I'm not sure about this. Right now 95% of the commits are from me, so I'm testing locally anyway and I have a nightly build running on my machine both to produce the zips on the downloads page and to catch things I miss when working locally (like 32bit, release, or linux only compile errors).

I don't have any automated testing yet, but even when I do I'm not sure how feasible it is to run graphics workloads on a service like this.

It's maybe something I would consider if I start getting regular/more contributions from others, if it is valuable in that case, but I think for now while it's just me this is unnecessary.

As a note (for future reference if nothing else): appveyor seems to be the service of choice for automated builds/tests on windows.

**Comment by cgmb** [comment]
That's fair. I found a CI to be a significant improvement over a nightly build, but that was when working with a number of other developers on an application with an extensive test suite. I can understand it being less valuable for renderdoc.

On another note, I like encapsulating suggestions as PRs if they affect a fairly small amount of code. It makes them a little easier to accept / decline. I know that some people could look at the fact that there's code and feed bad for declining, but if it were an actually significant amount of work, I'd talk to you about it first.

**Comment by baldurk** [comment]
Yeh there are a number of considerations I'd need to rethink if the project changed from being just a single developer. E.g. I have in mind that if I get more contributions I will likely set up a clang-format file to ease formatting issues, things like that.

CI could be an improvement if there are ever multiple active developers when it's more likely to unknowingly break things for other people - the idea can be revisited then. I do plan to set up automated testing even just to run locally the same as my nightly build, so maybe also in future I could investigate setting up automated testing somehow on PRs.

**Comment by cgmb** [comment]
Thanks for the heads-up on Appveyor. Like Travis, you can configure it with a YAML file in the root directory. Unlike Travis, it also gives the option of storing the configuration on their website instead. That makes it a lot easier to use it in a fork, so hurrah for Appveyor.

I finally got my local Windows build set up last night, but it's nice to have an automatic build so I don't need to reboot all the time. 9b853f86f0c2e89d2d34cf002c15c5633990b6a6 reminded me that I need to check things work on Windows, too.

A related benefit is that I can point you to build logs. I encountered build failures caused by structure size checks in `replay_proxy.cpp`, both on my local machine (Win 8.1, VS2015) and on Appveyor (VS2013,VS2015): https://ci.appveyor.com/project/cgmb/renderdoc/build/v0.28.3#L148

**Comment by baldurk** [comment]
Yeh I've noticed those, I should really fix them but I wanted to switch the checks to build in the x64 build instead - since most people rarely build Win32 and that's the only place they're turned on. Running them in x64 would make them easier to catch.

**Comment by cgmb** [comment]
For posterity, a basic `appveyor.yml` might look like so:
```
version: '{branch}.{build}'
build_script:
- cmd: '"C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\msbuild" "renderdoc.sln" /p:Configuration=Development /p:Platform=x64 /p:PlatformToolset=v140 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"'
```

**Pull request closed without merging**
