### PR TITLE
Added sampler type in GL pipeline viewer

### PR DESCRIPTION
**Pull request by imadr**
## Description

image

Added a column to the samplers table in the pipeline state viewer for OpenGL.
I put this PR together quickly, I'm not sure if it's the correct way to do it.

### CODE REVIEW

**Comment by baldurk** [comment]
Can you explain what problem you're trying to solve or what information that you're wanting to display that isn't already displayed? Comparison vs not comparison is already displayed so I'm not sure what you are trying to do exactly.

**Comment by imadr** [comment]
I'm trying to see the sampler type in the samplers list

Correct me if I'm wrong, but in OpenGL the compare func doesn't always correspond to the sampler type? Contrary to d3d where you can use any compare func https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-to-samplecmp

OpenGL sampler types https://www.khronos.org/opengl/wiki/Sampler_(GLSL)#Sampler_types
OpenGL comparison mode https://www.khronos.org/opengl/wiki/Sampler_Object#Comparison_mode

**Comment by baldurk** [comment]
A 'shadow' sampler as GL will call it is 1:1 with comparison mode being enabled - if comparison mode is enabled, you must use a shadow sampler, and vice-versa for a non-shadow sampler you cannot use comparison mode. This is outlined in the second link you posted:

> Using this mode requires two special settings. **First, the [sampler](https://www.khronos.org/opengl/wiki/Sampler_(GLSL)) used in GLSL must be a shadow sampler.** Second, the texture used in that sampler must have activated depth comparison mode. Attempting to use a texture without comparison with a shadow sampler, or vice-versa, will result in an error upon rendering.

In your screenshot the comparison mode is shown in the filter: `(Less Equal)`. The type column then seems redundant because it's showing the same information, unless I'm misunderstanding what you mean.

**Comment by imadr** [comment]
> A 'shadow' sampler as GL will call it is 1:1 with comparison mode being enabled 

Fair enough, I wasn't aware of that

**Pull request closed without merging**
