### PR TITLE
Fix uninitialized variable

### PR DESCRIPTION
**Pull request by Ace17**

### CODE REVIEW

**Comment by baldurk** [comment]
What is the bug or problem being here that motivated this change? This ID is only used to compare against the cache ID in the context to check for changes and should be initialised before first use, so it doesn't have to be initialised in the declaration like this.

**Comment by Ace17** [comment]
The problem here is that we're invoking undefined behaviour.
I found this problem using valgrind, which reports that at least one `if` branch is relying on the value of this variable.


image

**Comment by Ace17** [comment]
Initially, I was trying to solve the refresh issue below (The "Outputs" panel on the right )

image

This occurs on two different GNU/Linux PC ( nvidia and intel GPU), both with Vulkan and OpenGL.

**Comment by baldurk** [comment]
OK I see the issue, it's not undefined behaviour and it's harmless, but yes the first read will happen before it's updated.

The event browser has no relation to the texture viewer. If you're having an issue please open a bug report with steps to reproduce and I can investigate.

**Comment by Ace17** [comment]
> it's harmless

Indeed.

> The event browser has no relation to the texture viewer. If you're having an issue please open a bug report with steps to reproduce and I can investigate.

Yeah, but I'm afraid the display issue doesn't only affect the texture viewer.

Actually, it affects all the tabs on the right part of the window. This is why I ran valgrind on the whole tool ( knowing it would also report unrelated warnings ).

At the moment I'm trying to isolate the problematic behaviour, and it seems it *might* be specific to the Debian packaging ( I'm not able to reproduce the issue with the official binaries from https://github.com/baldurk/renderdoc/releases ).

So I believe more investigation is needed on my side.

**Comment by baldurk** [comment]
That seems very strange, it doesn't make sense for it to only affect things on one side of the window since the entire layout can entirely be re-arranged (you could mirror it such that the event browser is on the right, the texture viewer on the left, with the thumbnails on the left side of the texture viewer itself).

But yes if you do report an issue in future please ensure it can be reproduced on either a source build or the official binaries, I don't support distribution packages. Especially the debian package which I know makes a lot of unnecessary and potentially problematic changes and has been known to cause crashes in the past - I would generally not recommend using it.

**Comment by Ace17** [comment]
> That seems very strange, it doesn't make sense for it to only affect things on one side of the window since the entire layout can entirely be re-arranged (you could mirror it such that the event browser is on the right, the texture viewer on the left, with the thumbnails on the left side of the texture viewer itself).

Definitely.

My previous screenshot might have been misleading, so here's a picture of the display glitch, so you get a clearer idea ( I changed the window layout, to make it clear it's not a left/right issue ):

image

image

I confirm I'm not able to reproduce the issue with this official build: version v1.22 ( built from 387a9e57 ) (Qt version 5.15.2).
However, If I recompile renderdoc ( same commit : 387a9e57 ) from source, against Qt version 5.15.6, I get the same display glitch as above.

So, maybe, there's something incompatible between Qt 5.15.6 and the current renderdoc source code ?

**Comment by baldurk** [comment]
I tested building with 5.15.6 recently for a bug and it worked fine, so it's not as simple as that.

The comments of an unrelated pull request are not the appropriate place to discuss a bug. Please open a bug report with as much information as possible and specific steps I can follow to reproduce as this may be related to something else specific to your application and environment.

**Pull request merged**
