### PR TITLE
Fix detecting renderdoccmd as a replay application on android

### PR DESCRIPTION
**Pull request by pantosj**

### CODE REVIEW

**Comment by pantosj** [comment]
@cnorthrop This should fix the problem you described in #735, that I also experienced. Could you try this, please?

**Comment by baldurk** [comment]
The change looks fine to me, will merge once @cnorthrop gives a :+1:, but I don't understand how changing where the rename happens affects the dlsym call?

**Comment by cnorthrop** [comment]
Excellent, we'd spent the morning here trying to figure out why the symbols weren't being found, debugging the Android dynamic loader/namespaces/etc.  The real fix happening here is - changing which library is loaded by the java call.  The `AndroidManifest.xml` already points to `librenderdoccmd.so`, so the native activity is dlopening it.  By putting `librenderdoc.so` in a the java `System.loadLibrary` call, it was being pulled in *before* `librenderdoccmd.so`.  The symbols weren't being propagated back up the dependency chain.

We can actually tidy this up further by removing the `System.loadLibrary` call altogether.  I believe it is redundant now.  @pantosj, can you add that to your commit?

I've tested Vulkan with this commit (it works) and additionally removing the java call (and it still works).  If you could confirm GLES still works without the java call, then we're good.

Otherwise, this is great, thanks for digging in to it!

**Comment by cnorthrop** [comment]
The changes to remove the shared object load from java are here, if you'd like to cherry-pick and try them out with GLES:

> android: Remove redundant shared object load from java
> https://github.com/cnorthrop/renderdoc/commit/3b8cc30dccfa2ae7d587e80e992ce297ab829a40

**Comment by baldurk** [comment]
@pantosj I'll merge either if you add the extra change or say you'd like to take this as-is.

**Comment by pantosj** [comment]
@baldurk I think you should merge it now without @cnorthrop 's patch. Because after I applied that patch I got the following error:

```
AndroidRuntime: Shutting down VM
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: org.renderdoc.renderdoccmd, PID: 25661
AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.renderdoc.renderdoccmd/org.renderdoc.renderdoccmd.Loader}: java.lang.IllegalArgumentException: Unable to load native library: /data/app/org.renderdoc.renderdoccmd-1/lib/arm64/librenderdoccmd.so
AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:222)
AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)
AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7229)
AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Unable to load native library: /data/app/org.renderdoc.renderdoccmd-1/lib/arm64/librenderdoccmd.so
AndroidRuntime: 	at android.app.NativeActivity.onCreate(NativeActivity.java:182)
AndroidRuntime: 	at org.renderdoc.renderdoccmd.Loader.onCreate(Loader.java:15)
AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6876)
AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
AndroidRuntime: 	... 9 more

```

I've checked and the shared library exists on the specified path. I'm trying to figure out what the problem might be in my case.

**Pull request merged**
