### PR TITLE
Add support for VK_EXT_external_memory_host

### PR DESCRIPTION
**Pull request by pipehuffer**
## Description

This enables the VK_EXT_external_memory_host extension and serializes its respective structures and function.
Most of the structures' values are informative and don't meaningfully impact recording or replaying. Except that on replay, `VkImportMemoryHostPointerInfoEXT` is removed from `vkAllocateMemory` chain as the memory in `pHostPointer` does not exist, allowing memory to be created regularly.
Tested under Alpine Linux and Artix Linux, both with Mesa 23.0.3 and an AMD Radeon RX 480.

### CODE REVIEW

**Comment by baldurk** [comment]
Unfortunately I don't think this extension can be safely supported in general, at least not with simple enabled support like this - it may work in some cases but will break in others. From the first spec issue on this extension:

> 1) What memory type has to be used to import host pointers?
> 
> **RESOLVED**: Depends on the implementation. Applications have to use the new [vkGetMemoryHostPointerPropertiesEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#vkGetMemoryHostPointerPropertiesEXT) command to query the supported memory types for a particular host pointer. The reported memory types may include memory types that come from a memory heap that is otherwise not usable for regular memory object allocation and thus such a heap’s size may be zero.

Which means that on some drivers the memory types reported for use for with imported memory using this extension could be completely disjoint from those memory types without imported memory. This may also depend on the type of host allocation (which is outside the scope of the Vulkan API).

If this were a physical device feature or property then the extension could be conditionally supported. Similar to buffer device address, on drivers like that where it's impossible to support then it would not be reported but otherwise allowed. However because this is a per-object memory type query by the time this problem can be detected it's too late.

There are other challenges related to the ability to 'break out' of the intercepted API surface with external undetected access to the host pointer, that are a bit less likely under typical use of the extension but still present potential problems.

Since the extension is generally only used for debugging (by having a breadcrumb memory object that's still accessible after device loss without the need for synchronisation), I expect most applications will have a fallback in the case that the extension isn't supported or only use it optionally. You could also keep this change locally if you wanted, assuming you know you're only running on drivers that will be capture/replay friendly.

**Comment by absolutelynothelix** [comment]
@pipehuffer, i've decided to give your changes a try since i'm using the vk_ext_external_memory_host extension and i can't use renderdoc because of it but the extension still seems to be missing when running an application with renderdoc. am i missing something?

**Comment by pipehuffer** [comment]
@absolutelynothelix sorry for the late reply, but try checking renderdoc's log file.
You should also know that my use case for this is the same as Wine's: you mmap memory for a shared resource yourself, so this might not work for you like baldurk said.

**Comment by absolutelynothelix** [comment]
@pipehuffer, no need to worry, i'm also slow :) where i can find the renderdoc's log file? my problem is that my application checks if required extensions are available before enabling them and when i start my application with renderdoc it says that the vk_ext_external_memory_host extension is missing.

update: i managed to get it working! sorry, it seems that it was my fault: i confused installed renderdoc with it's local build.

**Pull request closed without merging**
