### PR TITLE
Fixed and extended modification of eglCreateContext's attribute lists

### PR DESCRIPTION
**Pull request by scottmarsland**
I fixed an issue in the looping of eglCreateContext's attribute list where it was going until the attribute name was 0 instead of EGL_NONE.

I've also added code to raise the requested context version to 3.2 or 3.1 depending on support. I first try 3.2 because if supported RenderDoc will end up using 3.2 functions (e.g. glIsEnabledi) instead of the extension versions. If not supported, I fallback to 3.1 as gl_rendertext requires it.

### CODE REVIEW

**Comment by baldurk** [comment]
I don't understand this change, you say "it was going until the attribute name was 0 instead of EGL_NONE." but EGL_NONE is defined to 0 so I don't see the distinction.

Also we definitely should not modify the version requested by the application during capturing, any changes to application behaviour should be as minimal as possible. Can you explain in more detail why you want to do that? You mention gl_rendertext requiring a version - if this is true it should be fixed instead.

**Comment by scottmarsland** [comment]
Hi,

EGL_NONE is a bit unintuitive and defined as 0x3038 in egl.h.

In the case of raising the context version. I'm experimenting with getting RenderDoc to work with Imagination Technology's PVRVFrame (libEGL/libGLESv2 emulation libraries) on Linux. Its context creation is a little stricter than most drivers so if you request a 3.1 context you'll literally get a 3.1 context. As a result you won't be able to use any 3.2 functions even if eglGetProcAddress returns them. Due to the way the real function pointers are loaded in RenderDoc in some situations it'll end up using 3.2 core functions even if the context is 3.1 e.g. glIsEnabledi will get used instead of glIsEnablediOES because eglGetProcAddress will return a valid function pointer for glIsEnabledi first. This is unfortunately why I added the attempt to raise the context to 3.2.

In the case of gl_rendertext, for its shaders it appear to be using glsl version 310 so requires a 3.1 context. For my testing I was using a simple application that only requested an ES 2.0 context so the rendertext shaders were failing to compile.

I do agree though, modifying the application behaviour isn't ideal but was the simpler fix.

Cheers,

Scott

**Comment by baldurk** [comment]
Eurgh, sorry that's my mistake, I assumed EGL_NONE was defined like GL_NONE to 0 and didn't check carefully when searching. That would be far too sensible...

I still think this should still be fixed elsewhere, fixing it like this could easily have knock-on effects elsewhere in more subtle ways as it's unknown what effect changing the version requested will have - it could even break application code that queries for the active version.

The problem you describe is similar to one on linux, where mesa will return function pointers for unsupported functions that just print an error message, so the code should generally handle checking explicitly for the necessary extensions before calling a function. It sounds like maybe this is just missing a couple of cases to account for GLES being different.

The text shaders should be pretty simple - they use GLSL 150 on desktop which is significantly older, so perhaps the GLES version could just be reduced? It's worth checking if the shaders actually use any features that aren't available in ESSL 200 - and if so which ones, since it should be possible to refactor the text rendering.

If you want to split apart the EGL_NONE fix that can be merged in, but the other changes I think will have to be reconsidered as above.

**Comment by scottmarsland** [comment]
No problem. I'll get the EGL_NONE fix split off now and will have a look at fixing the other issues in a different way.

**Pull request closed without merging**
