### PR TITLE
gearvr crash fix and mip level fix for gearvr swapchain

### PR DESCRIPTION
**Pull request by trs-jimmy-lee**
Simple fix

### CODE REVIEW

**Comment by baldurk** [comment]
Thanks for this, the travis failure is my fault, the code looks fine.

I now have an S8 available for testing, so is it possible for you to share or link to a simple gearvr example program that I can use for testing in future to make sure I don't break it again when making changes like this?

**Comment by trs-jimmy-lee** [comment]
Hi I am using the UnrealEngine 4 for testing. It already has renderdoc integration built in, so in the UE4 editor, under Project Settings>Android Graphics Debugger and set it to use RenderDoc and specify the root path to your renderdoc root, and then just build and push to phone.
Alternatively, using the demo supplied by the gearvr sample codes might be easier for you. Here is the link: https://developer.oculus.com/downloads/native-android/

**Comment by baldurk** [comment]
Thanks! I'll check that out. Also cool to know that Unreal has an option for it built in.

**Comment by baldurk** [comment]
@trs-jimmy-lee I tried to set this up today to test some changes coming that may affect the vrapi hooks, but unfortunately it seems like the samples won't run at all unless you have a gearvr headset plugged in. I guess this check is somewhere inside oculus's code, and from what I've been told I need to run at least once with the headset before I can run without.

Instead would you might checking that the vrapi hooking is still working on latest v1.x when you are able to?

Feel free to email me directly if you'd prefer.

**Comment by trs-jimmy-lee** [comment]
On your S8, if you go to gear vr service>more (on the upper right corner), there is a developer mode option. If you turn this on, you can run vr without putting on a headset, but the cpu also runs at a higher clock rate so it will drain your battery faster.

I am a little bit busy with another project for the next 2 weeks, but I will definitely take a look at it as soon as possible. Thank you for letting me know!

**Comment by baldurk** [comment]
Thanks, this pointed me in the right direction and I was able to test one of the samples.

Things at least aren't broken now with the latest changes, but it seems like unfortunately vrapi will be impossible to hook with the new method (mostly just because android is an awful platform made of endless pain and misery), so you'll still have to link against renderdoc's library. It's unfortunate but at least it's not worse than it was before.

**Comment by trs-jimmy-lee** [comment]
I know what you mean. But being able to debug and profile on Android is already a huge improvement for my workflow. I really appreciate the work you have done with RenderDoc, making it accessible to even Android!

**Pull request merged**
