### PR TITLE
Add support for VK_NV_linear_color_attachment

### PR DESCRIPTION
**Pull request by pdaniell-nv**
## Description

Adds support for [VK_NV_linear_color_attachment](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_NV_linear_color_attachment.html), which functionally is a noop for RenderDoc because it already supports the full Vulkan color attachment functionality, of which VK_NV_linear_color_attachment is a subset.

### CODE REVIEW

**Review by baldurk — CHANGES_REQUESTED** [review]
These changes look good to me as adding pure support, though can you squash the formatting commit into the original changes? Or squash it all together if you prefer. Generally I merge PRs with all commits intact assuming they are intended to be meaningfully separate so I ask that they're squashed by the PR author generally.

I'm also wondering though what testing you've done with this. You say that it's a no-op and that this extension is a subset of the normal rules but from my understanding I'm not sure if that is the case. This extension _expands_ the functionality but in a restricted way doesn't it? ie. allowing use of more formats/tiling/usage combinations as color attachments providing you obey more rules on them.

The reason I ask is because it means that any code in RenderDoc that substitutes the image views in a framebuffer expecting them to be freely mix-and-matchable will no longer work as is if I'm right because it breaks a new rule added in this extension. Now it could create an invalid framebuffer if it mixed in the wrong image view whereas before that was impossible because no such rule existed. That is something that at least the pixel history does, to find the full-float-precision output from shaders. Does that work with this extension unmodified?

**Comment by pdaniell-nv** [comment]
> These changes look good to me as adding pure support, though can you squash the formatting commit into the original changes?

Done.

> I'm also wondering though what testing you've done with this.

I've spot-tested this change with a simple test app to determine that a) the extension is allow-listed and my test application that requires it works b) a framebuffer with linear images can be created and used. I've tried several of the RenderDoc features like the Texture View and Resource Inspector and they all work. I see no evidence of RenderDoc internally swapping the image tiling between linear and optimal.

**Comment by baldurk** [comment]
OK thanks - could you try expanding your test app to do MRT with multiple colour attachments and then run the pixel history on one of them? I'm worried that will break due to substituting only one of the image views in the framebuffer.

**Comment by pdaniell-nv** [comment]
> That is something that at least the pixel history does, to find the full-float-precision output from shaders. Does that work with this extension unmodified?

I did not test pixel history, and now I see that's your right, this does have a problem. I'm going to put this change on hold (draft) until I can figure out how best to move forward.

**Comment by pdaniell-nv** [comment]
Closing this PR as I'm not able to put more time into this in the foreseeable future.

**Pull request closed without merging**
