### PR TITLE
Create a clone context with the same profile as the shared one

### PR DESCRIPTION
**Pull request by lephilousophe**
This matches behaviour of WGLPlatform

Without this patch, when an OpenGL context is created by the application, the clone context is OpenGL compatible as described in GLX_ARB_create_context.
It means it is neither ES nor Core profile.

It also helps for #2831 but is not enough.

### CODE REVIEW

**Comment by baldurk** [comment]
I think this makes sense, do I understand right then that the problem you saw before was during capture?

It's probably fine but I'm going to hold on merging it since I'm doing a stable release shortly and this has a high risk and it's a very niche bug. I don't understand though why you say this is not enough, or in the comments on the other PR (please keep discussion here to keep things clear) why you're talking about GL core profile.

**Comment by lephilousophe** [comment]
The problem was during the capture indeed.
I split the explanation because there are two bugs: cloned context is not really a clone and shader at gl_emulated.cpp:3010 doesn't set its version.

What I fix here is that when cloning the context, the cloned context is now of the same type as the original one (if the original is GLES it is GLES, if it is Core it will be Core).
Without this fix, the context created is always a backward compatible one.

On PR #2831, I fix a shader version.
This shader is only used on one occasion: when the software under test is using a GL_ALPHA Texture to store data (typically a paletized texture which uses another texture and a shader to make the rendering).
So, as soon as the software under test has a GL_ALPHA texture for this, RenderDoc calls its shader to dump the texture using a cloned context.

If the software under test is using GLES, the cloned context will be GLES (with this PR) and an unversioned shader will be considered as GLSL ES 1.0 (like if `#version` 100 was specified).
If the software under test is using GL Core, the cloned context will be GL Core and an unversioned shader will be considered as GLSL 1.1.
But, under GLSL 1.1, `precision` keyword doesn't exists and a compilation error is triggered.

If you don't have this PR (the current one), the cloned context being always GL (not ES), and an unversioned shader is always considered as GLSL 1.1.

**Comment by baldurk** [comment]
OK I think I see - there's a misunderstanding on the second part then. That code and shader only runs on GLES because it's emulating functionality that is missing in GLES (because GLES is a broken and strictly worse subset of GL - this functionality has existed since GL 1.0 in 1994!). So using the precision keyword unconditionally is fine because it's on a GLES-only path, this fix should be complete then if I have understood now.

This fix looks fine then to match API for cloned contexts since that will likely avoid problems anyway. As I say I won't merge this until after the next stable release to avoid potentially breaking things.

**Comment by lephilousophe** [comment]
OK, I was not sure when I read you about if this shader was used elsewhere.
So I think this bug is rarely exhibited: only when you have a GL implementation supporting GL and GLES and when you use GLES (which is my case with Mesa on Linux for ScummVM).

No need to hurry, the important is to have a fix which works. :)

**Pull request merged**
