### PR TITLE
rename custom event name

### PR DESCRIPTION
**Pull request by xoyojank**
## Description

add "Rename" to event item's context menu
image
image
image

### CODE REVIEW

**Comment by xoyojank** [comment]
This is useful for captures that do not contains any event markers

**Comment by baldurk** [comment]
I'm not necessarily opposed to a feature like this but I'm not convinced of its value. The application is much more easily able to produce markers itself, and can do so with more context. If your code isn't already producing markers then you should add markers to your code, which means those markers will be present in every capture instead of having to be manually re-applied and will work in any other tools you use. Why do you need to do this in RenderDoc?

**Comment by xoyojank** [comment]
> I'm not necessarily opposed to a feature like this but I'm not convinced of its value. The application is much more easily able to produce markers itself, and can do so with more context. If your code isn't already producing markers then you should add markers to your code, which means those markers will be present in every capture instead of having to be manually re-applied and will work in any other tools you use. Why do you need to do this in RenderDoc?

sometimes the app or game is not developed by ourself, so we cannot add markers in the code

**Comment by baldurk** [comment]
RenderDoc is only intended for capturing your own programs. Capturing copyrighted programs that you do not have the rights to is not endorsed and I will provide absolutely no support for it.

**Pull request closed without merging**
