### PR TITLE
POD array size check in serializer

### PR DESCRIPTION
**Pull request by kvark**

### CODE REVIEW

**Comment by baldurk** [comment]
This isn't a valid check, at least as far as my intention of the functions goes. There's no requirement that on reading there be any kind of valid value in the numElems field - even if it's quite common that this function is used for serialising fixed-size arrays where numElems will be valid. E.g. see [this callstack being serialised](https://github.com/baldurk/renderdoc/blob/master/renderdoc/driver/d3d11/d3d11_context.cpp#L909) where the array is NULL (to be allocated) and numElems is 0. But that's a coincidence, it's a deliberate choice that numElems doesn't have to be initialised to 0 to say 'I don't know how many elements there are'.

The distinction between POD and complex arrays when I split this function apart is that POD arrays can be serialised as one big block of memory memcpy'd around, and complex arrays have to have Serialise() called on each element.

Did you run into a bug or broken behaviour that you wanted to add this check for? Maybe that's worth investigating if there's a practical problem there where the sizes did mismatch.

**Comment by kvark** [comment]
Oh, true, this PR is lame, sorry :)

What I've been hitting is an access violation when `FinishCommandList` was called from the immediate context. Renderdoc just stops recording at this point but shows no error, so when I tried replaying this I was getting crashes. During a debug session, one of the things I hit was non-sensual POD array count, so I thought it would be good to at least work around it somehow.

To properly address this, it would be great for RenderDoc to show errors correctly both on recording and replaying.

**Comment by baldurk** [comment]
Yes calling FinishCommandList on an immediate context will go very badly, I'm not surprised the capture that was generated was garbage, it might even crash. In general RenderDoc isn't too tolerant of invalid API use - I try and handle it here and there but there are plenty of cases where passing in a NULL pointer where you're not allowed to will crash things. The only thing in this case is [an assertion](https://github.com/baldurk/renderdoc/blob/master/renderdoc/driver/d3d11/d3d11_context_wrap.cpp#L4685), which will print a log message but otherwise do nothing

I'm not sure what you mean about showing errors on recording and replaying. Any errors that are detected will be logged just the same in both cases.

**Comment by kvark** [comment]
Logging is just not enough. There should be no way of recording a broken capture, since it's guaranteed to cause trouble on replaying. If you detect that the recording failed, show some message to the user and delete the partially written capture. Sounds good?

**Comment by baldurk** [comment]
Under normal circumstances I agree, and it should do that currently - apart from renderdoc bugs of course which do still happen. But e.g. it's very easy to break a capture by mapping a buffer in your program and then overrunning the buffer - you will write into other serialised data and cause a guaranteed broken replay.

Renderdoc will not be able to capture in a couple of cases - if you Map() before the start of the captured frame, and Unmap() in the middle (then the map wasn't intercepted), or similarly if you replay a command list that wasn't captured in the frame. In those cases it will fail-over and try to capture the next frame in the hopes that this time it will work, and eventually give up if it just can't succeed. If it produces a .rdc file then that file should open and replay correctly - any other behaviour is a bug - but I don't detect or correct for invalid use of the API in general so that's 'undefined behaviour' including problems replaying.

**Comment by kvark** [comment]
What's the exact problem with FinishCommandList though? We call it, it fails, the list is NULL, but we never use it anyway. Perhaps, RenderDoc may have some code to handle it?

**Comment by baldurk** [comment]
You said you were calling it on the immediate context? As far as I understand it, that's invalid. It's only valid to call on a deferred command list for later execution on the immediate context. I think it will return [DXGI_ERROR_INVALID_CALL](https://msdn.microsoft.com/en-us/library/windows/desktop/ff476424(v=vs.85).aspx)

From [here](https://msdn.microsoft.com/en-us/library/windows/desktop/ff476887(v=vs.85).aspx)

> A command list must be created from a deferred context...

If you're seeing problems calling FinishCommandList on a deferred context, that's definitely a bug and I'll look into it - let me know any repro details you have.

In this case it would be easy to simply drop the call to FinishCommandList() if you call it on the immediate context - I guess that's what D3D11 does as well as logging to the D3D11 debug layer.

**Comment by kvark** [comment]
We were calling it from the immediate context, and we fixed it now. But during that time, the `.rdc` file was being generated but was failing to replay, which is what I'm concerned about.

**Comment by baldurk** [comment]
Yes so that's what I was saying originally. Once you go out of the bounds of legal API use all bets are off, I don't make any promises about whether or not renderdoc will crash, generate a garbage rdc, or what.

In this case I think what happened was all the chunks in the immediate context got moved elsewhere (to be used as a command list) and then were never inserted into the .rdc file. Unfortunately one of those chunks was the frame header chunk with important information in it, and it got lost - so where on replay a header chunk was expected, instead it got whichever was the first chunk recorded after the FinishCommandList call.

I will certainly put in a change to insert/log a warning and ignore the call to FinishCommandList from an immediate context, but there will be dozens of other similar ways that it can break. I do not think about invalid API use when designing renderdoc, and hardening the tool against it is a quite low priority that probably won't happen for a long time.

**Comment by kvark** [comment]
I believe you clearly see what's going on there. The explanation matches my experience when I was debugging it.

> I will certainly put in a change to insert/log a warning and ignore the call to FinishCommandList from an immediate context

Thanks!

> , but there will be dozens of other similar ways that it can break.

This is arguable. Messing with command lists is one thing that can screw up recording badly. Just passing wrong parameters to any of the states or even draw calls is not as critical for stability.

**Pull request closed without merging**
