### PR TITLE
[In progress] GLES allows drawing from client memory or without an explicit VAO.

### PR DESCRIPTION
**Pull request by michaelrgb**
In this case we will create a temporary VAO with VBOs if needed so that
input mesh data is recorded.

### CODE REVIEW

**Comment by baldurk** [comment]
Can you give more detail about what exactly is going on? A PR with no description or just the commit message is fine for small changes, but this needs more background about what's different in GLES and what the fix is going to be.

**Comment by michaelrgb** [comment]
Sorry. In core-profile GL we require an explicit VAO, as well as buffers for each attribute, i.e. no client memory is allowed. GLES is more relaxed in that it does allow client memory arrays, as long as no VAO is bound. It also allows buffers without a VAO.

RenderDoc records input mesh data by saving the currently bound attrib buffers. I wanted to find a way of supporting GLES with as little changes to the state saving code, therefore for every glDrawArrays we check at the last minute if we need to copy client memory to a temporary buffer, or if we need to assign those buffers into a temporary VAO.

**Comment by baldurk** [comment]
OK. The code should already handle the case of no VAO being bound; I found this is a pretty common thing that otherwise core-subset GL programs would do. Since supporting core only is a limitation of scope/effort rather than some ideological issue, I added support for a 'fake' VAO being bound instead of 0, so the replay is still core GL.

I understand right then, the case of no VAO & array buffers is already handled. The new case we need to handle is: if VAO 0 is bound and no array buffer is bound, `glVertexAttrib*Pointer` points to actual memory in the last parameter instead of an offset.

I'd suggest we handle this similarly to how we implement the fake VAO for object 0 - create say 16 array buffers for each potential attribute, initially sized to 64 bytes or something. Whenever we encounter one of these memory `glVertexAttribPointer` calls, treat it as a `glBindBuffer` + `glVertexAttribPointer` (with 0 offset) sequence and store the stride. Then when we come to a drawcall resize up the buffers if needed and insert the appropriate `glBufferSubData` calls to copy the data. On replay we create the buffers at the appropriate max size, and the replay works out the same.

It means creating a few buffers extra all the time but that's not the end of the world, and it means less work done per-draw. You can also just leave this behavior in as default any time we hit that case. Since it's undefined on existing GL we can just implement this legacy behaviour - it does no harm. You could insert a debug message about it to warn the user that they're using legacy/non-core functionality.

**Comment by michaelrgb** [comment]
Im not sure the case of no VAO but with buffers is recorded properly (not according to my test app and my understanding of the code).

In WrappedOpenGL::glVertexAttribPointer: 
```
GLResourceRecord *varecord = cd.m_VertexArrayRecord;
GLResourceRecord *r = m_State == WRITING_CAPFRAME ? m_ContextRecord : varecord;
if(r)
...
```
m_VertexArrayRecord is NULL when no VAO is bound, and therefore nothing will be serialized in glVertexAttribPointer. Does m_VertexArrayRecord need to point to the dummy VAO when nothing is bound?

**Comment by baldurk** [comment]
The fake 0 VAO is created and immediately marked dirty:

```cpp
    // register VAO 0 as a special VAO, so that it can be tracked if the app uses it
    // we immediately mark it dirty since the vertex array tracking functions expect a proper VAO
    m_FakeVAOID = GetResourceManager()->RegisterResource(VertexArrayRes(NULL, 0));
    GetResourceManager()->AddResourceRecord(m_FakeVAOID);
    GetResourceManager()->MarkDirtyResource(m_FakeVAOID);
```

So we don't need to try to record any updates to it before capframe. Since it's dirty, its initial state will be serialised out and used if it's referenced in the frame. In the case above during capframe the updates are recorded into the context record rather than any VAO record.

I haven't tested this path much since up until now it's only kicked in for non-core programs and it's only a "best-effort" attempt at some minor compatibility. I know it's worked in some cases in the past but I don't doubt there are some edge cases that break it.

**Comment by michaelrgb** [comment]
Ah what happens is that yes the buffer attrib pointers are stored into the m_ContextRecord IFF we call glVertexAttribPointer repeatedly inside the CAPFRAME. The problem is my app setup the attributes once at the beginning during the IDLE frame, which is normal app behaviour.

This logic definitely needs to be modified to call the Serialise_glVertexArrayVertexAttribOffsetEXT(...) during the WRITING_IDLE, which isnt happening at the moment.

**Comment by baldurk** [comment]
I don't follow exactly. With any VAO, we only track a certain number of pre-capture updates. In particular once we've seen a certain number (currently 64) then `RecordUpdateCheck` will fail and we'll bail out of the function.

We don't want to change that behaviour or start recording updates during WRITING_IDLE as then the capture will get bloated with redundant updates in the case that the application is performing VAO updates every frame instead of just at init time, which like you say is the normal way. The most common reason for this is an application which uses one global VAO and updates it constantly when changing vertex input setup.

The only difference with VAO 0 is that we start off dirty so it always acts like this limit has been hit. When the frame capture starts, we grab the initial contents of any VAO that's dirty (including the fake VAO 0), which will have the accumulated results of any updates that were dropped. If there's a problem with VAO 0 updates going missing, I think it's something slightly/subtly different.

**Comment by michaelrgb** [comment]
When I set RefAllResources=true I see the contents of my input mesh buffers with VAO 0. Obviously this is just a test to narrow it down.

For the real solution of the VAO 0 updates missing, in WrappedOpenGL::StartFrameCapture() is it possible that we need to pass MarkVAOReferenced(allowFake0=true) ? I tried that but it still didnt help, can you suggest anything else?

**Comment by michaelrgb** [comment]
Closed until I have the real fix.

**Comment by baldurk** [comment]
I found the fix locally this morning with a simple desktop GL app that uses VAO 0. You are right that `MarkVAOReferenced` call should pass `allowFake0=true`. When I stepped through it there were a couple of other things that weren't properly firing, e.g. if VAOs weren't shared then the context pointer didn't match VAO 0's, and there was an early-out checking for name 0 which is normally invalid. I'll push a fix shortly.

**Comment by michaelrgb** [comment]
Ah thanks :) Once Ive tested that I can go back to your plan for supporting client vertex pointers.

**Comment by baldurk** [comment]
Try with that commit (be86d52).

**Pull request closed without merging**
