### PR TITLE
Update glslang to 11.7.1

### PR DESCRIPTION
**Pull request by jljusten**
## Update glslang to 11.7.1

I'll admit that I've only done minor testing on this. Let me know if I can/should do more testing. I tested a simple GL and Vulkan program under Linux. With Vulkan I tried stepping through a couple spir-v shaders.

1. `glsl_shaders: Set glslang env input version to 0 for GL shaders`

This fixes an issue I encountered with glslang starting in 11.2.0. The details of the issue are in the commit message.

2. `shaders/spirv: Build changes for glslang 11.7.1`

I'm not 100% confident in this patch. I'm not sure that the "signed int warnings" start at gcc 11. I also only tried building under Linux, so windows could be broken.

3. `renderdoc/3rdparty/glslang: Update to release 11.7.1`

I copied the files over, but I avoided copying some files that it seems like renderdoc hasn't copied in the past. I may have this wrong though...

### CODE REVIEW

**Comment by baldurk** [comment]
Can you explain why this is needed, what's the reasoning for changing the version of glslang?

**Comment by jljusten** [comment]
> Can you explain why this is needed, what's the reasoning for changing the version of glslang?

I added some details in the commit message for the patch. Let me know if I should try to add more info there as well.

I didn't put this in the commit message, but the main readme sort of cryptically suggests that 0 might be useful in some cases:

https://github.com/KhronosGroup/glslang/#c-class-interface-new-preferred

**Comment by baldurk** [comment]
I'm sorry I don't see it. Of the three commits I can see two have mostly only title/subtitle type messages and a mention about being signed off by you, and the third only seems to explain some particular parameter change in the code.

**Comment by jljusten** [comment]
> I'm sorry I don't see it. Of the three commits I can see two have mostly only title/subtitle type messages and a mention about being signed off by you, and the third only seems to explain some particular parameter change in the code.

Oh, whoops. I misread your question. I thought you were concerned with the "version" change in the `glsl_shaders: Set glslang env input version to 0 for GL shaders` patch.

The only reason I could give is to not fall too far behind the released glslang version. It could make it a bit easier to update glslang in the future for a more compelling reason if too many issues, like this one, have not accumulated.

I mentioned on irc that debian currently uses glslang 11.7.1 with renderdoc, so I would definitely appreciate getting your feedback on the  `glsl_shaders: Set glslang env input version to 0 for GL shaders` patch, even if you are against using glslang 11.7.1 in renderdoc. Obviously you'd have a much better understanding of the renderdoc code, and I'd be great if you could prevent me from missing some big pitfall with the change which I hadn't considered.

**Comment by baldurk** [comment]
I'm afraid I don't want to update only for the sake of updating. I'm not sure it's reason enough to stay up to date to avoid more change in future if an update is needed for some othe reason.

Looking at the documentation in the headers for that parameter it doesn't seem like 0 would be an appropriate value, rather it should probably be the `version` passed in as used for the #version since `setEnvInput` is explicitly noted to be describing the source language not any target (e.g. SPIR-V or not). As I understand it from the documentation again, SPIR-V generation would be determined by the `EShTargetLanguage` being either `EShTargetNone` for validation/pre-processing of pure GL shaders only, or `EShTargetSpv` for SPIR-V generation.

I'm going to close this for now since I don't want to accept this PR without a stronger justification. If there's ambiguity in how the glslang API should be called I'd recommend opening an issue on glslang to get clarification as I can't say for certain either.

**Pull request closed without merging**
