### PR TITLE
add CMake funcion for determining current git rev

### PR DESCRIPTION
**Pull request by Marqin**
/GetGitHash.cmake has function get_git_hash that gives current
git rev hash or "NO_GIT_COMMIT_HASH_DEFINED" if we are
building out of git repo.
It's used in /renderdoc/CMakeLists.txt

### CODE REVIEW

**Comment by Marqin** [comment]
I have tested this on OS X in git repo and outside git repo (tested via "message()).

**Comment by Marqin** [comment]
It obviously failed when `git` was not installed. I've fixed it in newest commit.

**Comment by baldurk** [comment]
Would you mind putting the function inside the root CMakeLists.txt rather than in a seperate included .cmake? I might eventually move build support files into a separate subfolder, but for now I don't want to clutter the root dir more than necessary - it's already pretty messy.

**Comment by Marqin** [comment]
done

**Pull request merged**
