### PR TITLE
Update README.md to reflect OS support for Linux

### PR DESCRIPTION
**Pull request by huffman**
I can update the text if something else is preferred. It didn't look like OSX was fully supported so I didn't add that.

### CODE REVIEW

**Comment by baldurk** [comment]
Hey thanks for this. For reference the v0.x branch is soft-locked and future development will be on v1.x. This doesn't matter for a minor change like this but in case you make future PRs they should be targeted to v1.x and then I'll cherry pick anything that should go onto v0.x. I've added a note to CONTRIBUTING.md for this since it wasn't very clear from a new PR.

**Comment by huffman** [comment]
@baldurk Ok, np, I wlll make sure to make PRs against `v1.x` in the future! Admittedly, I just made a quick modification without reading contribution.md, so I may not have noticed it anyway :) - I wonder if it would make sense to set the default branch to `v1.x`?

**Comment by baldurk** [comment]
The default branch is set to `v0.x` so that someone arriving at the main page will get a stable and reliable version of the code, rather than `v1.x` where things will soon be in flux and changing a lot. It's unfortunate that I can't have a different branch for PR targets and the main page, but tbh that could be confusing in itself.

**Comment by huffman** [comment]
@baldurk Ah, makes sense! Thanks for the explanation.

**Pull request merged**
