### PR TITLE
Fix shader reflection pointers

### PR DESCRIPTION
**Pull request by tabikati**
In case of OpenGL the shaders are mutable and the shader
reflection cache is cleared in the replay proxy while the UI still uses
them resulting segfault. We disable the shader cache in this case to
resolve the problem.

### CODE REVIEW

**Comment by baldurk** [comment]
Thanks for identifying this issue, I think this might explain some reported crashes I've been seeing on android GL captures, which I've not been able to follow up on due to lack of contact info.

I don't think this fix is quite right though, since with your change then the shader reflection objects are going to continually leak memory, as they are allocated every time and then never deleted. Normally the shader cache keeps track of the lifetime and either re-using them or deleting them as appropriate.

I ran a test using GL over the remote proxy, and it seems like the problem kicks in e.g. when editing shaders, where a call to `ReplayLog` happens silently underneath the UI, which then deletes the shader reflection cache without the UI properly re-fetching the state and shader reflection objects. I think it would also happen in some other cases like opening a new panel with a preview display (like texture viewer or mesh output) which also does a `ReplayLog`. Is that what you're seeing?

One better fix would be to include the current EID in the shader cache key, for GL where the shaders are mutable. Unfortunately this is still going to mean the shader cache bloats in a way that's mostly unnecessary, but at least it won't keep allocating if the user selects the same event again, and the memory would be tracked and freed eventually.

If you'd like to make this fix yourself let me know, otherwise I'll commit it later today.

**Comment by tabikati** [comment]
This problem happens when we replay a capture on remote server and the initial data is loaded. The texture viewer, pipeline viewer and mesh viewer tabs are open. 

If we add the EID to the cache key, we still need to remove the cache clearing in the replay log, am I right? If yes, then I can modify the pull request to remove the cache clearing only and fix adding the EID key in a later pull request. Would it be ok for you?

**Comment by baldurk** [comment]
I committed the fix as described above, I wouldn't want to only half-fix it now when it could easily be fixed properly.

Let me know if that fixes it for you - I'm surprised you hit this case by only loading the capture since to my thinking there wouldn't be time for the UI to have some shader reflection pointers that are then invalidated, but hopefully this will fix it either way.

**Comment by tabikati** [comment]
I have checked your fix, it resolves the problem and works fine for me.

**Pull request closed without merging**
