### PR TITLE
Use ps -A when looking for PID of injected process.

### PR DESCRIPTION
**Pull request by michaelrgb**

### CODE REVIEW

**Comment by michaelrgb** [comment]
On another PC, adb shell ps was showing nothing except for ps itself, which is same as default behavior of ps on desktop.

**Comment by baldurk** [comment]
Presumably this is device-specific because that's where `ps` runs, rather than PC specific?

Do you know if this parameter is supported on all relevant android/device versions? If it's unsupported on Android 4.0 or similar that's not important. Is there a risk that we run `ps -A` and just get an error from an unknown parameter?

**Comment by michaelrgb** [comment]
I was actually using the same device on 2 different PCs (different distro versions), so its probably because of different adb versions. The software on the phone was exactly the same each time.

ps is an old standard tool, so Im fairly certain that parameter is widely supported too. But I can test it on more devices here if you want.

**Comment by baldurk** [comment]
That seems strange :disappointed:.

I _think_ in desktop `ps`, the parameter is lowercase `-a` for all processes, but looking at the source for android's custom `ps` the `-A` parameter has been around for a long time, so this should be safe to change.

**Comment by baldurk** [comment]
FYI surprising nobody I found a case where `ps` will just print an error message about a bad PID if you pass `-A` as a parameter. Upon investigation it seems like the `ps` binary is provided by `toolbox` which doesn't support the param and not `toybox` which does, even though it's Android 7.0 which should be using `toybox`.

I think the solution is just to try both variants and hope one of them produces some results. Then when we find an android install that doesn't work with either version we can just add another variant.

**Pull request merged**
