### PR TITLE
Vk pixel history: support various texture formats

### PR DESCRIPTION
**Pull request by apazylbe**

### CODE REVIEW

**Comment by apazylbe** [comment]
Just realized there is a problem here where ConvertComponent does not handle A component in B8G8R8A8 correctly. I am going to fix that.

**Review by baldurk — APPROVED** [review]
This looks fine to me. What's the bug in `ConvertComponent`? Do you want to fix that in this PR or in a follow-up PR? I'm fine either way.

**Comment by apazylbe** [comment]
So, as far as I understand, the A component should not be processed with the SRGB lookup table, but with my current code it would be because compType is UNormSRGB. 
Am I missing something?

**Comment by apazylbe** [comment]
I think I fixed it for pixel history use of ConvertComponent, but I do wonder if it should be fixed for general case inside ConvertComponent. I think it would need an extra parameter to figure out which component it is though.
Let me know if I am missing something though, I am less familiar with that code.

**Comment by baldurk** [comment]
Ah yes you're definitely right, I just didn't realise what you meant originally.

Indeed this should be fixed everywhere. Looking at it, currently `ConvertComponent` is always called in a loop over `compCount`, so I think it'd be better to change the function to return a `FloatVector` and convert all components at once. Either you or I can do that in a follow-up though, this is fine to merge as-is once CI is green.

**Pull request merged**
