### PR TITLE
Rudimentary glXGetCurrentContext hook

### PR DESCRIPTION
**Pull request by kvark**

### CODE REVIEW

**Comment by baldurk** [comment]
Thanks for the PR, but as I mentioned in #427 I'm already looking into sorting this out properly.

**Comment by kvark** [comment]
Your call, although I don't see how you implementing it properly disregards any of the changes I made.

**Comment by baldurk** [comment]
I just mean that I'm already working on making sure all GLX functions are exported properly, and the change I have locally will conflict with what you did so I'd just end up accepting mine in the merge anyway.

**Comment by kvark** [comment]
Great! Good to know :)

**Pull request closed without merging**
