### PR TITLE
Get default Activity on Android 6.0

### PR DESCRIPTION
**Pull request by tabikati**
"cmd package resolve-activity" is only available from Android 7.0. Pre Android 7.0 we can use "pm dump <packagename>" to get the default Activity name.

### CODE REVIEW

**Comment by baldurk** [comment]
Thank you for this, I'd discussed offline using `pm dump` to find the activity on android 6.

I don't have any problems with the code, it looks perfect and I like that it's a fallback after trying `cmd package`. I have a couple of higher level questions:

* I've seen `android.intent.action.MAIN` appear multiple times in the `pm dump` output. Do you need to look specifically for `android.intent.action.MAIN:` with the trailing `:` ?
* Have you tested this against packages with multiple different activities?

Also tagging @cnorthrop to check this as he was looking at android 6 support.

**Review by baldurk — APPROVED** [review]

**Comment by cnorthrop** [comment]
I hadn't found time to do this yet, so I appreciate the fix. :)

Looks good to me.  I just tested it with Marshmallow (6.0.1) on a Nexus6P and was able to connect and capture a frame from Fruit Ninja.  I ran into issues with other GLES apps, but nothing that looks related to activity name.

Thanks!

**Comment by tabikati** [comment]
In the `pm dump` output we are searching where the Activities with MAIN intent filter are listed, starting with this line exactly: 

> android.intent.action.MAIN:

 (with the „:”)

If there are more Activities with MAIN intent filter, the first one in the list is selected however it might not has LAUNCHER intent filter. Should we check if both intent filters are granted?

I have tried `cmd package resolve-activity -c android.intent.category.LAUNCHER` when there are more than one Activities with LAUNCHER intent filter and it doesn't work. (it tries to start com.android.internal.app.ResolverActivity)

**Comment by baldurk** [comment]
Interesting to hear, thanks. Yes I was wondering about the `:` because at the moment you have;

```cpp
  const char *intentFilter = "android.intent.action.MAIN";
```

So I was wondering if it would make sense to change it to look for `"android.intent.action.MAIN:"` with the `:`, so there's less chance it will find a different line than you expect. With everything else we've found with android I worry that there will be some android installations where the `pm dump` output is somehow different, so the more robust the parsing can be the better.

To be honest I don't understand android's activity system, it seems needlessly overcomplicated to me, I just wanted to raise some potential issues to be sure there wasn't an obvious problem. If the `resolve-activity` has issues with multiple activity apks in some situations that's a separate issue to consider, not related to this PR.

**Comment by tabikati** [comment]
I have modified the `intentFilter` to `"android.intent.action.MAIN:"`.

**Comment by baldurk** [comment]
Thanks again!

**Pull request merged**
