### PR TITLE
Refactor dynamic rendering setup code

### PR DESCRIPTION
**Pull request by ShabbyX**
Deduplicating code between BeginRenderPassAndApplyState and
FinishSuspendedRenderPass.  Fixes a bug where FinishSuspendedRenderPass
was using the depth attachment for stencil.

### CODE REVIEW

**Comment by ShabbyX** [comment]
@baldurk before adding more duplicate code here for MSRTSS, I went ahead and refactored the code. I took a `diff` of the functions to make sure they are the same, and turned out `FinishSuspendedRenderPass` had a bug where it was setting the `stencil` attachment to `depth`.

**Comment by ShabbyX** [comment]
Unfortunately I don't yet have access to anything with dynamic rendering support, so I'm afraid I'd have to rely on your verification of the change. Sorry.

**Comment by baldurk** [comment]
FWIW I believe every desktop vendor supports dynamic rendering in their latest drivers now on windows and linux, so unless you don't have a vulkan-capable GPU in your desktop at all then you may well have dynamic rendering support that way.

**Comment by ShabbyX** [comment]
Yes of course. It's just my workstation that's stuck on the 470 Nvidia driver for who knows why >:(

**Pull request merged**
