### PR TITLE
For replay, dlsym from libEGL.so instead of RTLD_NEXT.

### PR DESCRIPTION
**Pull request by michaelrgb**
RTLD_NEXT doesnt seem to work on Android O.

### CODE REVIEW

**Comment by michaelrgb** [comment]
Perhaps @cnorthrop and @galpeter would like to review this first.

I removed the LoadSymbolsFrom() parameter, as we now always get it from the global.

**Comment by galpeter** [comment]
Just a personal thing: I would like to keep the parameter for the LoadSymbolsFrom method just so it is decoupled from the global variable. IMHO the intent is more clear that way, that we are loading the symbols from the given handle.

If we however want to still add the global variable usage into the method then we should also rename it to something like LoadSymbols.

**Comment by michaelrgb** [comment]
No problem, restored the parameter and passed in the global.

Does this cause any issues for you?

**Comment by michaelrgb** [comment]
Peter approves of this. I think the CI failure was caused by a fixed Qt error.

**Comment by baldurk** [comment]
Yeh the Qt error was my bad.

I was waiting to give @cnorthrop a chance to look, although he's US based so probably not around this week. It's a little worrying that suddenly RTLD_NEXT stopped working, but I suppose even if it gets fixed (assuming it was unintentional) that doesn't help us :disappointed:.

**Comment by baldurk** [comment]
Before I merge - does this also work on desktop linux?

**Comment by michaelrgb** [comment]
I dont know if this is related, but Im getting the following crash on Linux loading a GLES capture:

```
1   ??                                                                                                                                                                                                                                                                   
2   glXChooseFBConfig                                                                                                                                                                                                            glx_hooks_linux.cpp 125  0x7ffff67fe26b 
3   ??                                                                                                                                                                                                                                                    0x7fffe563f877 
4   ??                                                                                                                                                                                                                                                    0x7fffe563fbbd 
5   ??                                                                                                                                                                                                                                                    0x7fffe563c1d9 
6   QXcbWindow::create()                                                                                                                                                                                                                                  0x7fffea0c2486 
7   QXcbIntegration::createPlatformWindow(QWindow *) const                                                                                                                                                                                                0x7fffea0ae820 
8   QWindowPrivate::create(bool)                                                                                                                                                                                                                          0x7ffff5161099 
9   QWidgetPrivate::create_sys(unsigned long long, bool, bool)                                                                                                                                                                                            0x7ffff59254c5 
10  QWidget::create(unsigned long long, bool, bool)                                                                                                                                                                                                       0x7ffff5924cbd 
11  QWidget::setVisible(bool)                                                                                                                                                                                                                             0x7ffff59311c9 
12  QDialog::setVisible(bool)                                                                                                                                                                                                                             0x7ffff5ad8d9d 
13  RDDialog::show                                                                                                                                                                                                               QRDUtils.cpp        885  0x555555be4a01 
14  RDDialog::<lambda()>::operator()(void) const                                                                                                                                                                                 QRDUtils.cpp        907  0x555555be4b42 
15  std::_Function_handler<void(), RDDialog::messageBox(QMessageBox::Icon, QWidget *, const QString&, const QString&, QMessageBox::StandardButtons, QMessageBox::StandardButton)::<lambda()>>::_M_invoke(const std::_Any_data &) functional          1731 0x555555be96ff 
16  std::function<void ()>::operator()() const                                                                                                                                                                                   functional          2127 0x555555bb5390 
17  GUIInvoke::doInvoke                                                                                                                                                                                                          QRDUtils.h          241  0x55555607ffaa 
18  GUIInvoke::qt_static_metacall                                                                                                                                                                                                moc_QRDUtils.cpp    69   0x55555607fb11 
19  QObject::event(QEvent *)                                                                                                                                                                                                                              0x7ffff4c40639 
20  QApplicationPrivate::notify_helper(QObject *, QEvent *)                                                                                                                                                                                               0x7ffff58ea35c 
... <More>                
```                                                                                                                                                                                                                                               

We should probably sort this out first.

**Comment by michaelrgb** [comment]
Sorry on Linux dlopen'ing libEGL loads up the Mesa Gallium driver, which conflicts with my active NVidia driver. Now we know the benefit of RTLD_NEXT.

I reverted this locally but it still crashes in CheckExtensions upon calling gl.glGetIntegerv()...

**Comment by cnorthrop** [comment]
I'm not aware of any problems with RTLD_NEXT, this is probably worth digging into farther.  I haven't spent any time exploring the GLES support in RenderDoc yet, so I don't have any good suggestions at the moment.  I'll be out until next week, but we'll want to get this fixed before v1.x.

**Comment by michaelrgb** [comment]
I think I know whats going on - qrenderdoc has loaded up both libGL.so (e.g. needed by Qt libraries) and libGLESv2_nvidia.so.2, which both supply an implementation of glGetIntegerv. Calling dlsym(libGLdlsymHandle, STRINGIZE(function)) gets the GL one, which crashes inside a GLES context.

Baldur could you try to create a simple capture on 1.0x from es2gears and replay it, to see if you get the same result?

**Comment by michaelrgb** [comment]
I had to remove the "GL.function = dlsym()" line - this is what breaks GLES for me on desktop. It seems to be fine to always get APIs from eglProcAddress/glxGetProcAddress. Are there any other situations where this wont work?

Ive tested this latest iteration on:
-es2gears (GLES)
-Simple desktop GL triangle app
-Replaying on Android N & O

**Comment by galpeter** [comment]
@michaelrgb imho switching to use the getprocaddress is a good idea. I've also wanted to create a change for that in a long time.

**Comment by baldurk** [comment]
I'm a little concerned about unexpected knock-on effects if we change what works on desktop GL. This is a particularly fragile area and I wouldn't be surprised if getprocaddress doesn't return a few functions on some old GL implementation on an obscure distribution.

I don't think anyone uses EGL on linux outside of test-cases (I could be wrong), so if we do need to drop the dlsym could we do it conditionally only in the EGL case, and leave the GL path alone?

**Comment by michaelrgb** [comment]
Agreed, playing it safe.

**Pull request merged**
