### PR TITLE
Added UNKNOWN vendor.

### PR DESCRIPTION
**Pull request by McNopper**
Otherwise member variable can be uninitialized and can cause a build fail.

### CODE REVIEW

**Comment by baldurk** [comment]
Hi, the change is fine but it must be formatted with clang-format to pass the travis test.

Can you also pull and rebase onto latest master? I just pushed some commits at about the same time and I think there's been some weirdness with the github PR merge commit. Your commit should rebase/cherry-pick cleanly, I didn't change anything near your code.

**Comment by McNopper** [comment]
Okay, did so.

**Comment by baldurk** [comment]
I've cherry-picked and squashed in the original commit for this PR, adding the UNKNOWN vendor (for future PR's it would be nice to rebase things - that way there aren't loads of merge commits and 'fix for clang-format' commits cluttering up the history).

In general it's not a good idea to continue pushing to a branch after you've opened a PR, unless it's to fix things with that particular PR. It's easier if you make a separate branch for the PR rather than using master, then you can continue as you like on other branches without affecting the on-going PR.

Feel free to open a new PR for the further commits, but watch out for commit message formatting too (See [CONTRIBUTING.md](https://github.com/baldurk/renderdoc/blob/master/CONTRIBUTING.md) for full details :smile:).

**Comment by McNopper** [comment]
Okay :-)

**Pull request closed without merging**
